version: '2'
services:

  webapi-backend:
    image: rancher-eco.westeurope.cloudapp.azure.com:8081/eco-vadis/platform-backend    
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    labels:
      io.rancher.container.pull_image: always

  frontend:
    image: rancher-eco.westeurope.cloudapp.azure.com:8081/eco-vadis/platform-frontend    
    restart: always
    labels:
      io.rancher.container.pull_image: always

  endpoint:
    image: rancher-eco.westeurope.cloudapp.azure.com:8081/eco-vadis/platform-endpoint
    ports:
      - 80:80
      - 443:443
    restart: always
    labels:
      io.rancher.container.pull_image: always 

  ##################################################
  ##                  DATABASE                    ##
  ##################################################
  
  one-mssqlserver:
    image: rancher-eco.westeurope.cloudapp.azure.com:8081/eco-vadis/platform-database    
    restart: always
    labels:
      io.rancher.container.pull_image: always     