version: '2'
services:

  webapi-backend:
    image: rancher-eco.westeurope.cloudapp.azure.com:8081/eco-vadis/platform-backend    
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    labels:
      io.rancher.container.pull_image: always

  frontend:
    image: rancher-eco.westeurope.cloudapp.azure.com:8081/eco-vadis/platform-frontend    
    restart: always
    labels:
      io.rancher.container.pull_image: always

  endpoint:
    image: rancher-eco.westeurope.cloudapp.azure.com:8081/eco-vadis/platform-endpoint
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /etc/letsencrypt/live/endpoint-eco.westeurope.cloudapp.azure.com/fullchain.pem:/certs/fullchain.pem
      - /etc/letsencrypt/live/endpoint-eco.westeurope.cloudapp.azure.com/privkey.pem:/certs/privkey.pem
    labels:
      io.rancher.container.pull_image: always 

  ##################################################
  ##                  DATABASE                    ##
  ##################################################
  
  one-mssqlserver:
    image: rancher-eco.westeurope.cloudapp.azure.com:8081/eco-vadis/platform-database    
    restart: always
    environment:        
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=5g6h7J8k9l
      - MSSQL_PID=Express
    labels:
      io.rancher.container.pull_image: always     