version: '2'
services:

  webapi-backend:
    scale: 1
    start_on_create: true

  frontend:
    scale: 1
    start_on_create: true

  endpoint:
    scale: 1
    start_on_create: true

  one-mssqlserver:
    scale: 1
    start_on_create: true